root: true

env:
    browser: true
    es2021: true
    jest/globals: true
extends:
    - react-app
    - react-app/jest
    - eslint:recommended
    - "plugin:react/recommended"
    - "plugin:jest/recommended"
    - prettier
parser: babel-eslint
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
settings:
    react:
        version: detect
plugins:
    - react
    - jest
rules:
    {
        react/react-in-jsx-scope: "off",
        react/function-component-definition: "off",
        react/jsx-filename-extension: "off",
        import/prefer-default-export: "off",
        react/prop-types: "off",
        no-unused-vars: "off"
    }
